# Generated by Django 5.2.6 on 2025-10-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitor',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF do Leitor'),
        ),
    ]
