<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-10-21 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_leitor_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.genero', verbose_name='Gênero do Livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.editora', verbose_name='Editora do Livro'),
        ),
    ]
=======
# Generated by Django 5.2.6 on 2025-10-21 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_leitor_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.genero', verbose_name='Gênero do Livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.editora', verbose_name='Editora do Livro'),
        ),
    ]
>>>>>>> 5aed052038bfd49e0fcc2ed04cff9b6c6d4e70cf
